### ISSUE TITLE
当blockquote标签内包含图片时无法显示

### ISSUE THREAD

**Issue by wiiiky** [hitoshii/letscorp#4]
BUG

**Comment by kevinfudan** [comment]
最新版本1.2.3于安卓6.0系统闪退。前一个版本没问题。

**Comment by wiiiky** [comment]
@kevinfudan 我的测试手机也是6.0系统，而且最新版本我也是在一些在线测试网站测试过。没有发现闪退的问题。我怀疑可能是版本升级数据库迁移没有做好（这个我确实忘了测试了）。你可以试试把应用卸载了重新安装；如果还是不行，请把你手机型号发给我，这样我可以进行测试；谢谢。

**Comment by wiiiky** [comment]
问题已经修复，当没有经过完整测试。因为测试用例不多。
